config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#home'
  
  
  resources :reviews
  resources :books do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :users
  resources :books

  get '/books', to: 'books#index'
  get '/books/:id', to: 'books#show'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  

  get '/auth/facebook/callback', to: 'sessions#login_with_fb'
  post '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :users, through: :reviews
    has_many :reviews
    validates :title, presence: true, uniqueness: true
    validates :author, presence: true
    validates :image_url, presence: true
    accepts_nested_attributes_for :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
    validates :comment, presence: true
    validates :title, presence: true
    
 

end

app/models/user.rb
class User < ApplicationRecord
    has_many :books, through: :reviews
    has_many :reviews
    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :name, presence: true, uniqueness: true
    #validates :password, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def home
         redirect_to login_path
    end

    def index
        
    end

    # def home
    #     redirect_to login_path
    # end

    

    def current_user
        @user ||= User.find_by(id: session[:user_id])
    end


     def logged_in?
       !!current_user
     end

   

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
        @book = Book.new
    end
    
    def create
       @book = Book.new(book_params)
       @book.save
       redirect_to books_path
    end

    def index
        @books = Book.all
    end

    def show
        @book = Book.find_by(id: params[:id])
    end

    private

    def book_params
        params.require(:books).permit(:title, :author, :image_url)
    end
end

app/controllers/reviews_controller.rb
require 'pry'
class ReviewsController < ApplicationController
    
    
    before_action :require_login
    
 
    
    def new
        @review = Review.new
        @book = Book.find_by_id(params[:book_id])
       # binding.pry
       

#         # if params[:book_id] && @review = Book.find(params[:book_id])
#             @review = @book.review.build
#   #         redirect_to book_path, alert: "What you're looking for isn't here! Please try again."
#          else
#             @review = Review.new
#         end
    end

    def create 

    binding.pry
     @review = Review.new(review_params)
     @review.user_id = session[:user_id]
        if @review.save
            redirect_to review_path(@review) 
        end
    end

    def index
        # if params[:book_id] && @review = Book.find(params[:book_id])
        #     @reviews = @book.reviews
        #     redirect_to book_path, alert: "What you're looking for isn't here! Please try again."
        # else
            @reviews = Review.all
        #end
    end

    def show
        
        # if params[:book_id]
        #    @book =  Book.find(id: params[:book_id])
        #    @review = @book.book.find(id: params[:id])
        # if @review == nil 
        #     redirect_to reviews_path(@book)
        #  end
        # else
            @review = Review.find_by(id: params[:id])
    end

    def edit
        @review =  Review.find_by(id: params[:id])
    end

    def update
        @review =  Review.find_by(id: params[:id])
        if @review.update(review_params)
            redirect_to review_path(@review)
        else  
            render :edit
        end
    end

    def destroy
        @review.destroy
        redirect_to review_path(@review)
    end

    private
    
    def review_params
        params.require(:review).permit(:title, :comment, :book_id)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
      end
end

app/controllers/sessions_controller.rb
require 'pry'
class SessionsController < ApplicationController

def home
    if logged_in?

        @reviews = current_user.reviews
    else
        redirect_to login_path
    end
end

def new
    
end

def create
    @user = User.find_by(email: params[:user][:email])
    #binding.pry
    if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    else
        flash[:error] = "Please try again"
       redirect_to login_path 
    end
end

def login_with_fb
    user = User.find_or_create_by(name: auth['email']) do |u|
        #binding.pry
    u.password = 'password'
    end
    user.save
    session[:user_id] = user.id
    redirect_to books_path
end

def destroy
    session.delete(:user_id)
    redirect_to root_path
end

private

def auth
    request.env['omniauth.auth']['info']
end

end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController

    def new
        @user = User.new
    #binding.pry
    end
    
    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else  
            render :new 
        end
     end

     def show
        @user = User.find_by_id(params[:id])
     end

private

    def user_params
        params.require(:user).permit(:name, :password, :email)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/undertower_helper.rb
module UndertowerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<h1> These are the books available to review! </h1>


<% @books.each do |b| %>
    
    <h3> <%= link_to b.title, book_path(b.id)%> </h3><br>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h2> By: <%= @book.author %> </h2>
<h3> Cover: <%= @book.image_url %> </h3>
<p><%= link_to "See All Reviews", review_path(@book) %></p>
<p><%= link_to "Add new Review", new_review_path(@book) %></p>
<h4>Reviews: </h4>
<% @book.reviews.each do |b|%>
<li><strong><%=b.user.name%></strong> says "<%=b.comment %>"</li>
<%end%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheUndertower</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/15ffe72ce5.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   

  </head>

  <div>
    <% if current_user %>
      <nav class="navbar navbar-inverse">
        <a class="navbar-brand" href="/">TheUndertower</a>
        <li><%= link_to "Add a new review", new_review_path %></li>
        <li><%= link_to "See all Books", books_path %></li>
        <li><%= link_to "See all Reviews", reviews_path %></li>
        <li><%= link_to "Logout!", logout_path, method: :post%></li>
  <% end %>
  </div>

  <div>
  <% if !current_user%>
  <nav class="navbar navbar-inverse">
    <%= link_to "Login!",  login_path %>
    <%= link_to "Signup!", new_user_path %>
    <%= link_to "Log in with Facebok", "/auth/facebook" %>

  </div>
  <% end %>
  </nav>




  <body>
 
    <%= yield %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/index.html.erb
z

app/views/reviews/edit.html.erb
<h1>Edit Your Review!</h1>

<%= form_for @review do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <%= f.submit "Edit!" %>
<% end %>

app/views/reviews/index.html.erb
<h1> These are the reviews other people have left! </h1>

<div class="container">
    <% @reviews.each do |r|%>
    <div> <%= r.title %> - <%= r.comment %> - <%= r.user.name %> </div>
    <% end %>
</div>

app/views/reviews/new.html.erb
<% render partial: "layouts/errors", locals: {object: @review} %>

<h1>Write a new review!</h1>
  <%= form_for @review do |f|%>
  <% if @book %>
  <% f.hidden_field :book_id, value: @book.id %>
  <% else %>
   <div>
   <%= f.label :book_id, "Pick a Title" %>
   <%= f.collection_select :book_id, Book.all, :id, :title, include_blank: 'Select One' %>
   </div>
  <% end %>

    <p>Write your review!</p>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %><br>
    </div>

   <div>
   <%= f.label :comment %>
   <%= f.text_area :comment %>
  </div>


  <%= f.submit "Submit!" %><br>
<% end %>

app/views/reviews/show.html.erb
<%= @review.title %> - <%= @review.comment%>

app/views/users/new.html.erb
  <%= form_for @user do |f|%>
    User Name:
    <%= f.text_field :name %><br>
    Email:
    <%= f.text_field :email %><br>
    Password:
    <%= f.password_field :password %><br>
    <%= f.submit "Log In!" %>
<% end %>

app/views/users/show.html.erb
This is the User show page